### PR TITLE
added the 2024 UQCS Hackathon project - Valostats

### PR DESCRIPTION
**Pull request by aman-86**
added "Valostats" - UQCS Hackathon 2024 project.

### CODE REVIEW

**Review by 49Indium — CHANGES_REQUESTED** [review]
Nice project; thanks for adding it to the showcase.
It seems that you have forgotten to include the image. Also, I think you have copied the "Best Presentation" caption by accident. Looking forward to getting your project up on the showcase.

**Comment by aman-86** [comment]
> Nice project; thanks for adding it to the showcase. It seems that you have forgotten to include the image. Also, I think you have copied the "Best Presentation" caption by accident. Looking forward to getting your project up on the showcase.

my bad. yeah it was by mistake. probably be happened while copying. let me fix it. however, how to add the image. I guess the public folder is hidden where you can put the images.

**Comment by 49Indium** [comment]
Images go in the `static/img/media/showcase/` directory. You can double check this has worked by using `hugo serve -D` within the folder of your fork of the repo on your machine (the [readme](https://github.com/UQComputingSociety/website/tree/main?tab=readme-ov-file#showcasing-your-project) has more information, though I'm happy to help).

**Comment by aman-86** [comment]
> Images go in the `static/img/media/showcase/` directory. You can double check this has worked by using `hugo serve -D` within the folder of your fork of the repo on your machine (the [readme](https://github.com/UQComputingSociety/website/tree/main?tab=readme-ov-file#showcasing-your-project) has more information, though I'm happy to help).

I have the necessary changes. please have a look now.

**Comment by 49Indium** [comment]
This was added with #343, so this PR is no longer needed.

**Pull request closed without merging**
