### PR TITLE
Update sponsor SVG for 2021 sponsors

### PR DESCRIPTION
**Pull request by mattchrlw**
As the title says

### CODE REVIEW

**Review by nicklambourne — CHANGES_REQUESTED** [review]
Can we use this one instead for Mycelium? That one just looks so out of place.

[https://mycelium.ventures/static/img/logo.png](https://mycelium.ventures/static/img/logo.png)

**Review by nicklambourne — APPROVED** [review]
ill-fitting logo used at the request of sponsor

**Review by nicklambourne — CHANGES_REQUESTED** [review]
Waiting for sponsor response to request to use reasonable logo.

**Review by kentonlam — APPROVED** [review]

**Review by JamesDearlove — APPROVED** [review]

**Comment by TomCranitch** [comment]
Sponsor has given the following as their preferred logo 

MYCELIUM WHITE

**Review by kentonlam — APPROVED** [review]

**Review by TomCranitch — APPROVED** [review]

**Review by JamesDearlove — APPROVED** [review]

**Review by nicklambourne — APPROVED** [review]

**Pull request merged**
