### PR TITLE
Add Sponsors. Fixes #61

### LINKED ISSUE #61: Featuring sponsors
Sponsor list needs to be updated.

Sponsor logos should also be added between the pagination buttons and the footer.

image

### PR DESCRIPTION
**Pull request by CameronAavik**
Can someone test this, I don't have ruby installed haha.

### CODE REVIEW

**Comment by TRManderson** [comment]
LGTM

**Comment by CameronAavik** [comment]
Don't merge this yet, need to get better logo for redback

**Comment by lewisjb** [comment]
image

**Comment by draganmarjanovic** [comment]
LGTM 👍  Cheers guys.

**Comment by gricey432** [comment]
@TRManderson "LGTM"

> Missing Polymathian

**Pull request merged**
