### PR TITLE
Added BeatHarder to showcase

### PR DESCRIPTION
**Pull request by henzo800**

### CODE REVIEW

**Review by bradleysigma — APPROVED** [review]

**Comment by bradleysigma** [comment]
Re-looking at this, the image isn't the same aspect ratio as the other showcase projects. Are you able to generate an image that has the same ratio? (Probably not too big of a deal if you can't.)

**Comment by henzo800** [comment]
I can touch up the image. What aspect ratio does it need to be? @bradleysigma

**Comment by bradleysigma** [comment]
1000px wide by 750px tall, anything else 4:3 at least that large.

**Comment by henzo800** [comment]
Updated Image. @bradleysigma 
Should be good to go :)

**Pull request merged**
