### PR TITLE
feat(website): add khwizmi to showcase

### PR DESCRIPTION
**Pull request by whenwe177**
Add Khwizmi to UQCS showcase

### CODE REVIEW

**Review by bradleysigma — APPROVED** [review]

**Comment by bradleysigma** [comment]
Re-looking at this, the image isn't the same aspect ratio as the other showcase projects. Are you able to generate an image that has the same ratio? (Probably not too big of a deal if you can't.)

**Review by LimaoC — CHANGES_REQUESTED** [review]
+1 to Bradley's comment. Would you be able to recreate a 1000x750 version?

**Comment by whenwe177** [comment]
Sorry for the delay, I've fixed the image size now.

**Review by LimaoC — APPROVED** [review]
lgtm, thanks for participating!

**Pull request merged**
