### PR TITLE
2024 Committee on About

### PR DESCRIPTION
**Pull request by JamesDearlove**
As we've now had 2 general meetings since the 2023 Committee was elected, this is to update the about page. Usually a job for current committee, but I felt it was time to get it done. As no images have been provided and I don't know Discord handles, placeholders have been added

image

### CODE REVIEW

**Comment by bradleysigma** [comment]
Please apply the `image-rendering: crisp-edges;` or `image-rendering: pixelated;` CSS property to these.

**Comment by JamesDearlove** [comment]
Ah thats what I missed, thank you. Now in their crisp pixelated rendering

image

**Comment by andrewj-brown** [comment]
Really, for maximum crispiness, you should re-make the images as SVG files. Pixel art shouldn't be too bad to work out vector coords for...

**Comment by bradleysigma** [comment]
drjoel

**Comment by jenseni-git** [comment]
Preferencing PR #323. Will close.

**Comment by JamesDearlove** [comment]
Disappointing, and understandable

**Pull request closed without merging**
