### PR TITLE
Redesign

### PR DESCRIPTION
**Pull request by draganmarjanovic**
The website has been redesigned completely. It would be interesting to collect some member projects and display them on the "Showcase" page.

### CODE REVIEW

**Comment by TRManderson** [comment]
:+1: Significant improvement. I'm for pulling it in. Committee is currently discussing it.

**Comment by svict4** [comment]
:+1:

**Comment by draganmarjanovic** [comment]
Yeah, no worries made the request so it's there :+1:

**Comment by ainsleynand** [comment]
Really like what you've done! All round looks fantastic and the design is refreshing :)

**Comment by draganmarjanovic** [comment]
Yeah, could be more amazing but my goal was just "better than current". Furthermore the bit that really excites me is the "showcase" page, the idea as I've mentioned countlessly is to showcase work done by UQCS members in the hope of getting more sponsors and building a better rep. :)

**Comment by svict4** [comment]
Yep @draganmarjanovic totally agree. Projects that are endorsed by the club helps members get noticed and adds weight to their CV.

**Pull request merged**
