### PR TITLE
Updated sponsor list

### PR DESCRIPTION
**Pull request by campbell-mcfadden**
Updating the list of sponsors on the homepage

### CODE REVIEW

**Comment by JamesDearlove** [comment]
Just a question, is there a reason that the new sponsor is not in alphabetical order with the other sponsors?

**Comment by campbell-mcfadden** [comment]
> Just a question, is there a reason that the new sponsor is not in alphabetical order with the other sponsors?

Not at all, I am just a bot 🤖 lol

**Review by JamesDearlove — APPROVED** [review]
Approving on the basis I have literally no say about this banner or its contents

**Review by Thomas-Malcolm — APPROVED** [review]
LGTM

**Pull request merged**
