### PR TITLE
Removed broken links 

### PR DESCRIPTION
**Pull request by zakaria-soufiani**
removed http://inciteful.net and https://flappyarm.xyz fixes issue #89

### CODE REVIEW

**Comment by CameronAavik** [comment]
@matthew-lake @draganmarjanovic @JoshuaRiddell 
Tagging you both since it is your links being removed here. Do you have an updated link to Inciteful (matthew) or FlappyArm (dragan/josh)?

**Comment by matthew-lake** [comment]
You can go ahead and remove Inciteful, the API it depends on is dead anyway.

**Comment by draganmarjanovic** [comment]
Ours is dead aswell. 😢

**Comment by draganmarjanovic** [comment]
Thanks @zakaria-soufiani .

**Comment by zakaria-soufiani** [comment]
Awesome ! You're welcome @draganmarjanovic

**Pull request merged**
