### PR TITLE
Revert "Revert "Recreating the UQCS Showcase (#219)" (#220)"

### PR DESCRIPTION
**Pull request by bradleysigma**
This reverts commit 5b2c59d7764b0239977f513ae9ceb6e130ab981c.

### CODE REVIEW

**Comment by nicklambourne** [comment]
Unless the issues have been fixed I see no need to undo to reversion.

**Comment by bradleysigma** [comment]
@kentonlam inherited this from me as of last night.
(Also, we need _something_ by the Hackathon.)

**Comment by kentonlam** [comment]
There will be something by hackathon.

**Comment by kentonlam** [comment]
image

**Comment by bradleysigma** [comment]
Pending reviewers: [...] @kentonlam

**Review by nicklambourne — APPROVED** [review]

**Pull request merged**
