### PR TITLE
Recreating the UQCS Showcase

### PR DESCRIPTION
**Pull request by bradleysigma**
This will almost certainly not work, and if it does, it will probably look exceedingly ugly, but it's a start.
It would be good to have somewhere for Hackathon 2020 attendees to display their work.

### CODE REVIEW

**Comment by kentonlam** [comment]
I think you'll need to set up the showcase-item shortcode template. Alternatively, just remove the showcase-image and rewrite it in HTML.

See https://github.com/UQComputingSociety/website/blob/master/content/about/_index.html and https://github.com/UQComputingSociety/website/blob/master/layouts/shortcodes/committee-photo.html

**Comment by jdcaperon** [comment]
If you can be bothered, you can read up on Hugo List Pages and Single Pages, this would give you pagination/infinite scroll and easy to add more elements for free.

**Review by kentonlam — CHANGES_REQUESTED** [review]
I know this is just a start, but we can do better than [this](https://user-images.githubusercontent.com/39479354/94994006-324e5000-05d8-11eb-825f-44a97b63ca25.png). At the very least, remove the double navbar, uncircle the images and fix the bolding 🙂

**Review by kentonlam — APPROVED** [review]
This is acceptable, barely.

**Comment by bradleysigma** [comment]
I strive for adequacy.

**Pull request merged**
