### PR TITLE
Updated 2023 list of sponsors

### PR DESCRIPTION
**Pull request by campbell-mcfadden**
It ain't much but it's honest work.

### CODE REVIEW

**Review by nicklambourne — APPROVED** [review]
Looking good 👌 

Screenshot 2023-03-27 at 12 27 14 pm

**Review by LimaoC — APPROVED** [review]
lgtm

**Review by JamesDearlove — APPROVED** [review]
lgtm

**Review by RachelChiong — APPROVED** [review]
Lgtm

**Pull request merged**
