### PR TITLE
Add share buttons and slack button

### PR DESCRIPTION
**Pull request by somebody1234**
## Screenshot
screenshot_20170302_120446

### CODE REVIEW

**Comment by lewisjb** [comment]
Would you be able to post screenshots?

**Comment by somebody1234** [comment]
Yeah, wait a sec, adding the other PR

**Comment by lewisjb** [comment]
Thanks! They look really neat in my opinion! Have you thought about adding them to the bottom of the page aswell? (ie the logo next to the text)

**Comment by somebody1234** [comment]
Not yet, will try now

**Comment by somebody1234** [comment]
Done, anything I should change? Resized the images after I took the screenshot so it won't be vertically off-center. Should I add more spacing between the text and the icons?

share_buttons_foot

**Comment by lewisjb** [comment]
If they are no-longer off-center then they look good to me. Should wait for some more feedback though :)

**Comment by draganmarjanovic** [comment]
I quite like it @somebody1234 - great work for taking the initiative! I'm not sure about having the icons colored in the footer, I feel they may be better monochrome - but regardless, I'm giving this an up-vote and will merge it (once everything is up and running). 👍

**Comment by TRManderson** [comment]
I'm happy for a merge :+1:. Will probably get around to sorting out deployment again soon.

**Comment by lewisjb** [comment]
Now that builds are working again, can this be merged?

**Comment by draganmarjanovic** [comment]
@lewisjb Thanks for reminding me. I will do this now 👍

**Pull request merged**
