### PR TITLE
Update about page for 2023 exec

### PR DESCRIPTION
**Pull request by LimaoC**

### CODE REVIEW

**Comment by JamesDearlove** [comment]
Preview so everyone doesn't have to clone:

image

**Comment by bradleysigma** [comment]
I would put Media, Events, Sponsors and Design on the second row.

**Comment by JamesDearlove** [comment]
Opinion: Personally, I think that the officers should all be on the one line, below T3. It just feels off with the officer titles being scattered throughout.

**Comment by bradleysigma** [comment]
bUt tHe t3 ArE OfFiCeRs.

**Comment by LimaoC** [comment]
That's fair, I'm not opposed to that either

**Review by JamesDearlove — APPROVED** [review]
image

**Comment by bradleysigma** [comment]
I'd go by the election order for the officers (which it might be already ¯\_(ツ)_/¯), and alphabetical by last name for the others.

**Pull request merged**
